CREATE DATABASE TAREFAS_DB;

USE TAREFAS_DB;

CREATE TABLE STATUSENUM (
    ID INT PRIMARY KEY,
    DESCRICAO NVARCHAR(50) NOT NULL
);

INSERT INTO StatusEnum(ID, DESCRICAO) VALUES(0, 'Pendente'),(1, 'EmProgresso'),(2, 'Concluida');

CREATE TABLE TAREFAS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TITULO NVARCHAR(100) NOT NULL,
    DESCRICAO NVARCHAR(255),
    DATACRIACAO DATETIME DEFAULT GETDATE(),
    DATACONCLUSAO DATETIME,
    STATUSID INT NOT NULL,
    FOREIGN KEY (STATUSID) REFERENCES STATUSENUM(ID) 
);